<FirstScreen>:
    GridLayout:
        cols: 1
        padding: 10
        spacing: 10
        Image:
            id: img
            size_hint_y: 0.8
        TextInput:
            id: user_query
            size_hint_y: 0.1
        Button:
            text: 'Search Image'
            size_hint_y: 0.1
            on_press: root.setImage()



<RootWidget>:
    FirstScreen:
        id: firstScreen
        name: 'first_screen'
